# Generated by Django 4.0.2 on 2022-02-24 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='mobile_no',
            new_name='mobile',
        ),
    ]
